import { useState } from 'react';
import { Icon } from '../components/Icon';
import { Modal } from '../components/ui/Modal';
import { PageHeader } from '../components/ui/PageHeader';
import { View } from '../components/View';
import { useToast } from '../contexts/ToastContext';
import { button, buttonGhost, buttonGhostSmall, buttonSmall, card, fieldLabel, heading, selectInput, table, tableWrap, textInput } from '../styles';

export type AdminSection = 'cohorts' | 'content' | 'adminClasses' | 'assessments' | 'projects' | 'adminCerts';

export function AdminOperations({ section }: { section: AdminSection }) {
  if (section === 'cohorts') return <Cohorts />;
  if (section === 'content') return <ContentLibrary />;
  if (section === 'adminClasses') return <ClassManager />;
  if (section === 'assessments') return <Assessments />;
  if (section === 'projects') return <Projects />;
  return <CertificateManager />;
}

function Cohorts() {
  const { toast } = useToast();
  const [formOpen, setFormOpen] = useState(false);
  const [cohorts, setCohorts] = useState([
    { name: 'Cohort 7', dates: '1 Sep – 16 Oct 2026', students: 43, courses: 2, status: 'Active' },
    { name: 'Cohort 8', dates: '5 Oct – 20 Nov 2026', students: 18, courses: 3, status: 'Enrolling' },
    { name: 'Cohort 6', dates: '6 Jul – 21 Aug 2026', students: 31, courses: 1, status: 'Completed' },
  ]);
  return <View><PageHeader description="Group students into delivery periods, assign courses and facilitators, and monitor each cohort as one learning unit." actionLabel="Create cohort" onAction={() => setFormOpen(true)} />
    <div className="grid gap-4 md:grid-cols-3">{cohorts.map((cohort) => <article key={cohort.name} className={card}><div className="flex items-start justify-between gap-3"><span className="grid size-10 place-items-center rounded-full bg-hq-red-ink text-sm font-bold text-hq-bone">{cohort.name.split(' ')[1]}</span><span className="rounded-[99px] bg-surface-2 px-2.5 py-1 text-xs font-semibold">{cohort.status}</span></div><h2 className="mt-5 text-xl font-[680]">{cohort.name}</h2><p className="mt-1 text-sm text-muted">{cohort.dates}</p><dl className="mt-5 grid grid-cols-2 gap-4 border-y border-line py-4"><div><dt className="text-xs text-muted">Students</dt><dd className="text-xl font-bold">{cohort.students}</dd></div><div><dt className="text-xs text-muted">Courses</dt><dd className="text-xl font-bold">{cohort.courses}</dd></div></dl><div className="mt-4 flex gap-2"><button className={buttonGhostSmall} type="button" onClick={() => toast(`${cohort.name} workspace opened.`)}>Manage</button><button className="grid size-9 place-items-center rounded-full hover:bg-surface-2" type="button"><Icon name="more" /></button></div></article>)}</div>
    {formOpen && <Modal title="Create a cohort" subtitle="Define the delivery dates, enrolment cap, courses, and facilitator team." onClose={() => setFormOpen(false)}><form className="grid gap-4" onSubmit={(e) => { e.preventDefault(); setCohorts((list) => [...list, { name: `Cohort ${list.length + 6}`, dates: '1 Dec 2026 – 22 Jan 2027', students: 0, courses: 2, status: 'Draft' }]); setFormOpen(false); toast('Cohort created.'); }}><div><label className={fieldLabel}>Cohort name</label><input className={`${textInput} w-full`} placeholder="e.g. Cohort 9" required /></div><div className="grid gap-4 sm:grid-cols-2"><div><label className={fieldLabel}>Starts</label><input className={`${textInput} w-full`} type="date" required /></div><div><label className={fieldLabel}>Ends</label><input className={`${textInput} w-full`} type="date" required /></div></div><div><label className={fieldLabel}>Courses</label><select className={selectInput} multiple size={3}><option>Advanced React Patterns</option><option>TypeScript for Product Teams</option><option>Design Systems with Tailwind</option></select></div><div className="grid gap-4 sm:grid-cols-2"><div><label className={fieldLabel}>Lead facilitator</label><select className={selectInput}><option>Kemi Adeyemi</option><option>Dr. Amaka Obi</option></select></div><div><label className={fieldLabel}>Student cap</label><input className={`${textInput} w-full`} type="number" defaultValue={30} /></div></div><button className={button} type="submit">Create cohort</button></form></Modal>}
  </View>;
}

function ContentLibrary() {
  const { toast } = useToast();
  const [uploaded, setUploaded] = useState(false);
  const items = [['Hooks vs render props', 'Video', '58:12', 'Advanced React Patterns', '14 Sep'], ['Compound components transcript', 'PDF', '184 KB', 'Advanced React Patterns', 'Today'], ['State machine starter', 'ZIP', '32 KB', 'Advanced React Patterns', '31 Aug'], ['Generics workbook', 'PDF', '1.2 MB', 'TypeScript for Product Teams', '12 Sep'], ['Course welcome', 'Audio', '08:24', 'Shared library', '1 Sep']];
  return <View><PageHeader description="A reusable library for video, audio, PDFs, downloads, links, and class recordings." actionLabel="Upload content" onAction={() => setUploaded(true)} />
    {uploaded && <div className="mb-5 rounded-[18px] border-2 border-dashed border-accent bg-[color-mix(in_srgb,var(--accent)_6%,transparent)] p-6"><div className="flex flex-wrap items-center gap-4"><Icon name="file" className="size-8 text-accent-text" /><div className="flex-1"><b className="block">course-outline.pdf</b><span className="text-sm text-muted">2.4 MB · Upload complete</span></div><select className={`${selectInput} w-auto`}><option>Advanced React Patterns</option><option>Shared library</option></select><button className={buttonSmall} type="button" onClick={() => { setUploaded(false); toast('Content added to the library.'); }}>Add to library</button></div></div>}
    <button className="mb-6 grid w-full place-items-center rounded-[20px] border-2 border-dashed border-line p-8 text-center hover:border-accent" type="button" onClick={() => setUploaded(true)}><span><Icon name="upload" className="mx-auto mb-2 size-7 text-accent-text" /><b className="block">Drop files here or browse</b><span className="text-sm text-muted">Video, audio, PDF, documents, images, and ZIP resources up to 2 GB</span></span></button>
    <div className={tableWrap}><table className={table}><thead><tr><th>Content</th><th>Type</th><th>Size / duration</th><th>Used in</th><th>Added</th><th /></tr></thead><tbody>{items.map((item) => <tr key={item[0]}><td><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-lg bg-surface-2"><Icon name={item[1] === 'Video' ? 'video' : item[1] === 'Audio' ? 'play' : item[1] === 'ZIP' ? 'folder' : 'file'} className="size-4" /></span><b>{item[0]}</b></div></td><td>{item[1]}</td><td>{item[2]}</td><td>{item[3]}</td><td>{item[4]}</td><td><button type="button" className="grid size-8 place-items-center"><Icon name="more" /></button></td></tr>)}</tbody></table></div>
  </View>;
}

function ClassManager() {
  const { toast } = useToast();
  const [open, setOpen] = useState(false);
  const classes = [['Compound components', 'Advanced React Patterns', 'Today, 4:00 pm', 'Kemi Adeyemi', 'Ready'], ['Generics in practice', 'TypeScript for Product Teams', 'Thu, 5:00 pm', 'Dr. Amaka Obi', 'Scheduled'], ['Performance patterns', 'Advanced React Patterns', 'Mon, 4:00 pm', 'Kemi Adeyemi', 'Draft']];
  return <View><PageHeader description="Schedule Zoom classes, control when links appear, assign hosts, and attach recordings after each session." actionLabel="Schedule class" onAction={() => setOpen(true)} />
    <div className="grid gap-4">{classes.map((item, index) => <article key={item[0]} className={`${card} grid items-center gap-4 md:grid-cols-[auto_minmax(0,1fr)_160px_150px_auto]`}><span className={`grid size-12 place-items-center rounded-full ${index === 0 ? 'bg-accent text-white' : 'bg-surface-2'}`}><Icon name="video" /></span><div><b className="block text-base">{item[0]}</b><span className="text-sm text-muted">{item[1]}</span></div><div><span className="block text-xs text-muted">When</span><b className="text-sm">{item[2]}</b></div><div><span className="block text-xs text-muted">Host</span><b className="text-sm">{item[3]}</b></div><div className="flex gap-2"><button className={index === 0 ? buttonSmall : buttonGhostSmall} type="button" onClick={() => toast(index === 0 ? 'Opening Zoom host controls.' : 'Class editor opened.')}>{index === 0 ? 'Start' : 'Edit'}</button><button className="grid size-9 place-items-center" type="button"><Icon name="more" /></button></div></article>)}</div>
    {open && <Modal title="Schedule a live class" subtitle="Students will see the class in their dashboard and course schedule." onClose={() => setOpen(false)}><form className="grid gap-4" onSubmit={(e) => { e.preventDefault(); setOpen(false); toast('Live class scheduled and students notified.'); }}><div><label className={fieldLabel}>Class title</label><input className={`${textInput} w-full`} required /></div><div><label className={fieldLabel}>Course and module</label><select className={selectInput}><option>Advanced React Patterns · Composition</option><option>TypeScript for Product Teams · Generics</option></select></div><div className="grid gap-4 sm:grid-cols-2"><div><label className={fieldLabel}>Date</label><input className={`${textInput} w-full`} type="date" required /></div><div><label className={fieldLabel}>Start time</label><input className={`${textInput} w-full`} type="time" required /></div></div><div className="grid gap-4 sm:grid-cols-2"><div><label className={fieldLabel}>Duration</label><select className={selectInput}><option>60 minutes</option><option>90 minutes</option><option>120 minutes</option></select></div><div><label className={fieldLabel}>Host</label><select className={selectInput}><option>Kemi Adeyemi</option><option>Dr. Amaka Obi</option></select></div></div><div><label className={fieldLabel}>Zoom meeting URL</label><input className={`${textInput} w-full`} type="url" placeholder="https://zoom.us/j/…" /></div><label className="flex gap-3 text-sm"><input className="mt-1 accent-[var(--accent)]" type="checkbox" defaultChecked />Notify enrolled students immediately.</label><button className={button} type="submit">Schedule class</button></form></Modal>}
  </View>;
}

function Assessments() {
  const { toast } = useToast();
  const [open, setOpen] = useState(false);
  const rows = [['Quiz 6: Composition', 'Advanced React Patterns', '10 questions', '80%', 'Published'], ['Mid-course exam', 'Advanced React Patterns', '30 questions', '70%', 'Scheduled'], ['Generics checkpoint', 'TypeScript for Product Teams', '12 questions', '75%', 'Draft']];
  return <View><PageHeader description="Build multiple-choice, true/false, and written assessments with independent scores, attempts, and progression rules." actionLabel="Create assessment" onAction={() => setOpen(true)} />
    <div className={tableWrap}><table className={table}><thead><tr><th>Assessment</th><th>Course</th><th>Questions</th><th>Passing score</th><th>Status</th><th /></tr></thead><tbody>{rows.map((row) => <tr key={row[0]}><td><b>{row[0]}</b></td><td>{row[1]}</td><td>{row[2]}</td><td>{row[3]}</td><td><span className="rounded-[99px] bg-surface-2 px-2.5 py-1 text-xs font-semibold">{row[4]}</span></td><td><button className={buttonGhostSmall} type="button" onClick={() => toast(`${row[0]} editor opened.`)}>Edit</button></td></tr>)}</tbody></table></div>
    {open && <Modal title="Create an assessment" subtitle="Set the rules first, then add questions in the question builder." onClose={() => setOpen(false)}><form className="grid gap-4" onSubmit={(e) => { e.preventDefault(); setOpen(false); toast('Assessment created. Question builder is ready.'); }}><div><label className={fieldLabel}>Assessment title</label><input className={`${textInput} w-full`} required /></div><div><label className={fieldLabel}>Course and module</label><select className={selectInput}><option>Advanced React Patterns · Composition</option><option>TypeScript for Product Teams · Generics</option></select></div><div className="grid gap-4 sm:grid-cols-2"><div><label className={fieldLabel}>Passing score</label><input className={`${textInput} w-full`} type="number" defaultValue={80} /></div><div><label className={fieldLabel}>Attempts</label><select className={selectInput}><option>3 attempts</option><option>Unlimited</option><option>1 attempt</option></select></div></div><fieldset><legend className={fieldLabel}>Question types</legend><div className="grid gap-2 sm:grid-cols-3">{['Multiple choice', 'True / false', 'Written response'].map((type) => <label key={type} className="rounded-xl border border-line p-3 text-sm"><input type="checkbox" defaultChecked className="mr-2 accent-[var(--accent)]" />{type}</label>)}</div></fieldset><button className={button} type="submit">Create and add questions</button></form></Modal>}
  </View>;
}

function Projects() {
  const { toast } = useToast();
  const columns = [{ title: 'Not submitted', count: 18, items: ['Headless data table', 'Design token pipeline'] }, { title: 'In review', count: 4, items: ['Zainab · Data table', 'Tunde · Token pipeline', 'Ngozi · Tabs API'] }, { title: 'Revision required', count: 2, items: ['Amina · Reducer refactor'] }, { title: 'Approved', count: 39, items: ['Femi · Form model', 'Chidera · State chart'] }];
  return <View><PageHeader description="Monitor assignment and final-project flow from brief through submission, facilitator review, revision, and approval." actionLabel="Create project brief" onAction={() => toast('Project brief editor opened.')} />
    <div className="grid gap-4 xl:grid-cols-4">{columns.map((column) => <section key={column.title} className="rounded-[18px] bg-surface-2 p-3"><div className="flex items-center justify-between px-2 py-1"><h2 className="font-[650]">{column.title}</h2><span className="rounded-full bg-background px-2 py-0.5 text-xs font-bold">{column.count}</span></div><div className="mt-3 grid gap-2">{column.items.map((item) => <button key={item} type="button" className="rounded-xl border border-line bg-surface p-3 text-left text-sm hover:border-foreground" onClick={() => toast(`${item} opened.`)}><b className="block">{item}</b><span className="mt-1 block text-xs text-muted">Advanced React Patterns</span></button>)}</div></section>)}</div>
  </View>;
}

function CertificateManager() {
  const { toast } = useToast();
  const [template, setTemplate] = useState('Academy standard');
  const issued = [['Ngozi Eze', 'Design Systems with Tailwind', '21 Sep 2026', 'HQ-7F3K-2291'], ['Femi Balogun', 'Product Foundations', '18 Sep 2026', 'HQ-4H8P-1044'], ['Zainab Idris', 'Design Systems with Tailwind', '12 Sep 2026', 'HQ-9J2M-7710']];
  return <View><PageHeader description="Configure branded templates, eligibility, signatories, and the immutable certificate record." actionLabel="Create template" onAction={() => toast('Certificate template editor opened.')} />
    <div className="grid gap-7 min-[1021px]:grid-cols-[minmax(260px,360px)_minmax(0,1fr)]"><aside><h2 className={heading}>Templates</h2>{['Academy standard', 'Professional programme', 'Workshop completion'].map((item) => <button key={item} className="mb-2 block w-full rounded-[14px] border border-line p-4 text-left aria-pressed:border-foreground aria-pressed:bg-surface" type="button" aria-pressed={template === item} onClick={() => setTemplate(item)}><b className="block">{item}</b><span className="text-sm text-muted">Landscape · Circle HQ branding</span></button>)}</aside><section><div className="relative aspect-[1.414/1] max-w-[680px] rounded-lg bg-[#f7f2e7] p-[5%] text-center text-hq-ink shadow-[0_24px_60px_-30px_rgb(0_0_0/.5)] before:absolute before:inset-[3%] before:border-[3px] before:border-hq-red after:absolute after:inset-[4.5%] after:border after:border-hq-amber"><div className="relative z-10 flex h-full flex-col items-center justify-center"><small>Circle HQ Academy certificate of completion</small><h3 className="mt-3 text-[clamp(18px,3vw,30px)] font-bold">{template}</h3><p className="mt-3 text-sm text-[#6f685d]">Awarded when all configured course conditions are complete.</p><div className="mt-5 h-px w-1/2 bg-hq-amber" /><b className="mt-2 text-lg">Student name</b><span className="absolute right-[4%] bottom-[2%] grid size-[13%] rotate-[-8deg] place-items-center rounded-full bg-hq-amber text-[clamp(7px,1.2vw,12px)] font-extrabold text-hq-red-ink">HQ<br />VERIFIED</span></div></div><div className="mt-5 flex flex-wrap gap-3"><button className={button} type="button" onClick={() => toast('Template changes saved.')}><Icon name="save" />Save template</button><button className={buttonGhost} type="button" onClick={() => toast('Test certificate generated.')}>Generate test certificate</button></div></section></div>
    <h2 className={`${heading} mt-10`}>Recently issued</h2><div className={tableWrap}><table className={table}><thead><tr><th>Student</th><th>Course</th><th>Completion date</th><th>Certificate ID</th><th /></tr></thead><tbody>{issued.map((row) => <tr key={row[3]}><td><b>{row[0]}</b></td><td>{row[1]}</td><td>{row[2]}</td><td className="font-mono text-xs">{row[3]}</td><td><button className={buttonGhostSmall} type="button" onClick={() => toast('Certificate record opened.')}>View</button></td></tr>)}</tbody></table></div>
  </View>;
}
