import { useState } from 'react';
import { Icon } from '../components/Icon';
import { ProgressRing } from '../components/ProgressRing';
import { View } from '../components/View';
import { CLASS_ACTIVITIES, ROSTER } from '../data/lms';
import { useToast } from '../contexts/ToastContext';
import { agenda, button, buttonGhostSmall, buttonSmall, card, fieldLabel, heading, muted, selectInput, table, tableWrap, textInput } from '../styles';

export function FacilitatorStudents() {
  const { toast } = useToast();
  const [selected, setSelected] = useState(ROSTER[0]);
  const [query, setQuery] = useState('');
  const visible = ROSTER.filter((student) => student.name.toLowerCase().includes(query.toLowerCase()));
  return <View><div className="mb-6 flex flex-wrap items-center gap-3"><label className="relative min-w-[240px] flex-1"><Icon name="search" className="absolute top-1/2 left-3.5 size-4 -translate-y-1/2 text-muted" /><input className={`${textInput} w-full pl-10`} placeholder="Search students" value={query} onChange={(e) => setQuery(e.target.value)} /></label><select className={`${selectInput} w-auto min-w-[170px]`}><option>All assigned courses</option><option>Advanced React Patterns</option><option>TypeScript for Product Teams</option></select></div>
    <div className="grid gap-8 min-[1021px]:grid-cols-[minmax(280px,380px)_minmax(0,1fr)]"><aside className="grid content-start gap-2">{visible.map((student) => <button key={student.name} type="button" aria-pressed={student.name === selected.name} className="grid grid-cols-[auto_1fr] items-center gap-3 rounded-[14px] border border-transparent p-3 text-left hover:bg-surface aria-pressed:border-foreground aria-pressed:bg-surface" onClick={() => setSelected(student)}><ProgressRing value={student.p} /><span><b className="block">{student.name}</b><span className="block text-sm text-muted">{student.course}</span><span className="mt-1 block text-xs capitalize text-muted">{student.status} · {student.detail}</span></span></button>)}</aside><section>
      <div className="flex flex-wrap items-start justify-between gap-4"><div className="flex items-center gap-3"><span className="grid size-12 place-items-center rounded-full bg-hq-red-ink font-bold text-hq-bone">{selected.initials}</span><div><h2 className="text-2xl font-[700]">{selected.name}</h2><p className={muted}>{selected.course}</p></div></div><button className={buttonSmall} type="button" onClick={() => toast(`Message sent to ${selected.name.split(' ')[0]}.`)}><Icon name="mail" />Send note</button></div>
      <div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">{[[`${selected.p}%`, 'Course progress'], ['84%', 'Quiz average'], ['5 / 6', 'Classes attended'], ['2', 'Submissions']].map(([value, label]) => <div key={label} className="border-y border-line p-4"><b className="block text-2xl font-[730]">{value}</b><span className="text-xs text-muted">{label}</span></div>)}</div>
      <div className="mt-6 grid gap-5 md:grid-cols-2"><div className={card}><h3 className={heading}>Learning timeline</h3><ul className="grid gap-4">{['Quiz 6 passed · 84%', 'Assignment 5 approved', 'Week 5 replay watched', 'Assignment 4 submitted'].map((item, index) => <li key={item} className="flex gap-3"><span className={`mt-1.5 size-2.5 shrink-0 rounded-full ${index === 0 ? 'bg-accent' : 'bg-reward'}`} /><span><b className="block text-sm">{item}</b><span className="text-xs text-muted">{index === 0 ? 'Today' : `${index + 1} days ago`}</span></span></li>)}</ul></div><div className={card}><h3 className={heading}>Facilitator notes</h3><textarea className="min-h-28 w-full rounded-xl border border-line bg-background p-3 text-sm outline-none focus:border-accent" placeholder="Private note about this student's progress…" /><button className={`${buttonGhostSmall} mt-3`} type="button" onClick={() => toast('Private note saved.')}>Save private note</button></div></div>
    </section></div></View>;
}

export function FacilitatorResults() {
  const { toast } = useToast();
  const results = [['Ngozi Eze', 'Quiz 6: Composition', '84%', 'Passed', 'Today'], ['Chidera Nwosu', 'Quiz 6: Composition', '62%', 'Retry available', 'Yesterday'], ['Femi Balogun', 'Generics checkpoint', '—', 'Not attempted', 'Due Thu'], ['Amina Yusuf', 'Mid-course exam', '76%', 'Passed', '14 Sep'], ['Tunde Bakare', 'Generics checkpoint', '91%', 'Passed', '13 Sep']];
  return <View><div className="mb-7 grid grid-cols-2 gap-3 sm:grid-cols-4">{[['81%', 'Average score'], ['86%', 'Pass rate'], ['7', 'Need retry'], ['3', 'Written answers']].map(([value, label]) => <div key={label} className="border-y border-line p-4"><b className="block text-3xl font-[740]">{value}</b><span className="text-sm text-muted">{label}</span></div>)}</div><div className="mb-5 flex flex-wrap gap-3"><select className={`${selectInput} w-auto`}><option>Advanced React Patterns</option><option>TypeScript for Product Teams</option></select><select className={`${selectInput} w-auto`}><option>All assessments</option><option>Quiz 6: Composition</option><option>Mid-course exam</option></select><button className={buttonGhostSmall} type="button" onClick={() => toast('Results exported as CSV.')}>Export results</button></div><div className={tableWrap}><table className={table}><thead><tr><th>Student</th><th>Assessment</th><th>Score</th><th>Outcome</th><th>Completed</th><th /></tr></thead><tbody>{results.map((row) => <tr key={`${row[0]}-${row[1]}`}><td><b>{row[0]}</b></td><td>{row[1]}</td><td className="font-bold">{row[2]}</td><td><span className="rounded-[99px] bg-surface-2 px-2.5 py-1 text-xs font-semibold">{row[3]}</span></td><td>{row[4]}</td><td><button className={buttonGhostSmall} type="button" onClick={() => toast(`${row[0]}'s answers opened.`)}>Review</button></td></tr>)}</tbody></table></div></View>;
}

export function FacilitatorClasses() {
  const { toast } = useToast();
  const [agendaText, setAgendaText] = useState('Review compound API trade-offs\nLive build: accessible tabs\nQ&A and assignment briefing');
  return <View><div className="grid gap-8 min-[1021px]:grid-cols-[minmax(0,1.2fr)_minmax(300px,.8fr)]"><section><h2 className={heading}>Class schedule</h2><ul className={agenda}>{CLASS_ACTIVITIES.map((item) => <li key={item.title}><div><b>{item.title}</b><span>{item.when}</span></div><button className={item.state === 'today' ? buttonSmall : buttonGhostSmall} type="button" onClick={() => toast(item.toast)}>{item.action}</button></li>)}</ul><div className={`${card} mt-6`}><div className="flex items-center justify-between"><div><h3 className={heading}>Attendance follow-up</h3><p className="text-sm text-muted">3 students missed two or more recent live classes.</p></div><Icon name="users" className="size-7 text-accent-text" /></div><button className={`${buttonGhostSmall} mt-4`} type="button" onClick={() => toast('Attendance reminder sent to 3 students.')}>Send reminder</button></div></section><section><div className={card}><h2 className={heading}>Edit next class</h2><div className="grid gap-4"><div><label className={fieldLabel}>Title</label><input className={`${textInput} w-full`} defaultValue="Compound components" /></div><div className="grid gap-3 sm:grid-cols-2 min-[1021px]:grid-cols-1"><div><label className={fieldLabel}>Date</label><input className={`${textInput} w-full`} type="date" defaultValue="2026-09-21" /></div><div><label className={fieldLabel}>Time</label><input className={`${textInput} w-full`} type="time" defaultValue="16:00" /></div></div><div><label className={fieldLabel}>Agenda</label><textarea className="min-h-36 w-full rounded-xl border border-line bg-background p-3 outline-none focus:border-accent" value={agendaText} onChange={(e) => setAgendaText(e.target.value)} /></div><div className="flex gap-2"><button className={button} type="button" onClick={() => toast('Class changes saved and students notified.')}><Icon name="save" />Save</button><button className={buttonGhostSmall} type="button" onClick={() => toast('Zoom host link copied.')}>Copy host link</button></div></div></div></section></div></View>;
}
