export const queryKeys = {
  auth: { me: ["auth", "me"] as const },
  announcements: { feed: ["announcements"] as const, admin: ["admin", "announcements"] as const },
  student: {
    dashboard: ["student", "dashboard"] as const,
    courses: (search = "") => ["student", "courses", search] as const,
    learning: (courseId: string) => ["student", "courses", courseId, "learning"] as const,
    assignments: (courseId = "") => ["student", "assignments", courseId] as const,
    submissions: (courseId = "") => ["student", "submissions", courseId] as const,
    certificates: ["student", "certificates"] as const,
    completion: (courseId: string) => ["student", "courses", courseId, "completion"] as const,
    certificate: (courseId: string) => ["student", "courses", courseId, "certificate"] as const,
    replays: ["student", "replays"] as const,
    liveClasses: ["student", "live-classes"] as const,
    studySessions: (courseId = "") => ["student", "study-sessions", courseId] as const,
  },
  facilitator: {
    dashboard: ["facilitator", "dashboard"] as const,
    students: (courseId: string) => ["facilitator", "courses", courseId, "students"] as const,
    submissions: (courseId: string, status = "") => ["facilitator", "courses", courseId, "submissions", status] as const,
    results: (courseId: string) => ["facilitator", "courses", courseId, "assessment-results"] as const,
    liveClasses: (courseId: string) => ["facilitator", "courses", courseId, "live-classes"] as const,
  },
  admin: {
    dashboard: ["admin", "dashboard"] as const,
    accounts: (role = "", status = "", search = "") => ["admin", "accounts", role, status, search] as const,
    courses: (status = "", search = "") => ["admin", "courses", status, search] as const,
    content: (courseId: string) => ["admin", "courses", courseId, "content"] as const,
    progress: (courseId: string) => ["admin", "courses", courseId, "progress"] as const,
    cohorts: (courseId: string) => ["admin", "courses", courseId, "cohorts"] as const,
    liveClasses: (courseId: string) => ["admin", "courses", courseId, "live-classes"] as const,
    assessments: (courseId: string) => ["admin", "courses", courseId, "assessments"] as const,
    projects: (courseId: string, status: "DRAFT" | "PUBLISHED" | "ARCHIVED") => ["admin", "courses", courseId, "projects", status] as const,
    submissions: (courseId: string, status = "") => ["admin", "courses", courseId, "submissions", status] as const,
    certificates: (courseId: string) => ["admin", "courses", courseId, "certificates"] as const,
    completionRequirements: (courseId: string) => ["admin", "courses", courseId, "completion-requirements"] as const,
    certificateTemplate: (courseId: string) => ["admin", "courses", courseId, "certificate-template"] as const,
    student: (studentId: string) => ["admin", "students", studentId] as const,
    studentCourses: (studentId: string) => ["admin", "students", studentId, "courses"] as const,
    studentAssessments: (studentId: string) => ["admin", "students", studentId, "assessments"] as const,
    studentSubmissions: (studentId: string) => ["admin", "students", studentId, "submissions"] as const,
    studentLiveClasses: (studentId: string) => ["admin", "students", studentId, "live-classes"] as const,
    studentCertificates: (studentId: string) => ["admin", "students", studentId, "certificates"] as const,
    studentActivity: (studentId: string) => ["admin", "students", studentId, "activity"] as const,
  },
} as const;

export const endpoints = {
  uploads: "/uploads",
  auth: {
    register: "/auth/register",
    verifyEmail: "/auth/verify-email",
    resendVerification: "/auth/resend-verification",
    login: "/auth/login",
    forgotPassword: "/auth/forgot-password",
    resetPassword: "/auth/reset-password",
    me: "/auth/me",
    changePassword: "/auth/change-password",
  },
  admin: {
    accounts: "/admin/accounts",
    account: (accountId: string) => `/admin/accounts/${accountId}`,
    accountStatus: (accountId: string) => `/admin/accounts/${accountId}/status`,
    pendingAccounts: "/admin/accounts/pending-approval",
    approveAccount: (accountId: string) => `/admin/accounts/${accountId}/approve`,
    rejectAccount: (accountId: string) => `/admin/accounts/${accountId}/reject`,
    dashboard: "/admin/dashboard",
    courses: "/admin/courses",
    course: (courseId: string) => `/admin/courses/${courseId}`,
    duplicateCourse: (courseId: string) => `/admin/courses/${courseId}/duplicate`,
    courseContent: (courseId: string) => `/admin/courses/${courseId}/content`,
    courseStatus: (courseId: string) => `/admin/courses/${courseId}/status`,
    courseProgress: (courseId: string) => `/admin/courses/${courseId}/progress`,
    modules: (courseId: string) => `/admin/courses/${courseId}/modules`,
    module: (moduleId: string) => `/admin/modules/${moduleId}`,
    lessons: (moduleId: string) => `/admin/modules/${moduleId}/lessons`,
    lesson: (lessonId: string) => `/admin/lessons/${lessonId}`,
    resources: (lessonId: string) => `/admin/lessons/${lessonId}/resources`,
    resource: (resourceId: string) => `/admin/resources/${resourceId}`,
    enrollments: (courseId: string) => `/admin/courses/${courseId}/enrollments`,
    facilitators: (courseId: string) => `/admin/courses/${courseId}/facilitators`,
    facilitator: (courseId: string, accountId: string) => `/admin/courses/${courseId}/facilitators/${accountId}`,
    assessments: (courseId: string) => `/admin/courses/${courseId}/assessments`,
    assessment: (assessmentId: string) => `/admin/assessments/${assessmentId}`,
    duplicateAssessment: (assessmentId: string) => `/admin/assessments/${assessmentId}/duplicate`,
    assessmentContent: (assessmentId: string) => `/admin/assessments/${assessmentId}/content`,
    projects: (courseId: string) => `/admin/courses/${courseId}/projects`,
    project: (projectId: string) => `/admin/projects/${projectId}`,
    projectStatus: (projectId: string) => `/admin/projects/${projectId}/status`,
    assessmentResults: (courseId: string) => `/admin/courses/${courseId}/assessment-results`,
    assessmentStatus: (assessmentId: string) => `/admin/assessments/${assessmentId}/status`,
    questions: (assessmentId: string) => `/admin/assessments/${assessmentId}/questions`,
    options: (questionId: string) => `/admin/questions/${questionId}/options`,
    submissions: (courseId: string) => `/admin/courses/${courseId}/submissions`,
    student: (studentId: string) => `/admin/students/${studentId}`,
    studentCourses: (studentId: string) => `/admin/students/${studentId}/courses`,
    studentAssessments: (studentId: string) => `/admin/students/${studentId}/assessments`,
    studentSubmissions: (studentId: string) => `/admin/students/${studentId}/submissions`,
    studentLiveClasses: (studentId: string) => `/admin/students/${studentId}/live-classes`,
    studentCertificates: (studentId: string) => `/admin/students/${studentId}/certificates`,
    studentActivity: (studentId: string) => `/admin/students/${studentId}/activity`,
    cohorts: (courseId: string) => `/admin/courses/${courseId}/cohorts`,
    cohort: (cohortId: string) => `/admin/cohorts/${cohortId}`,
    duplicateCohort: (cohortId: string) => `/admin/cohorts/${cohortId}/duplicate`,
    cohortStatus: (cohortId: string) => `/admin/cohorts/${cohortId}/status`,
    cohortStudents: (cohortId: string) => `/admin/cohorts/${cohortId}/students`,
    cohortStudent: (cohortId: string, accountId: string) => `/admin/cohorts/${cohortId}/students/${accountId}`,
    cohortFacilitators: (cohortId: string) => `/admin/cohorts/${cohortId}/facilitators`,
    liveClasses: (courseId: string) => `/admin/courses/${courseId}/live-classes`,
    liveClass: (liveClassId: string) => `/admin/live-classes/${liveClassId}`,
    liveClassStatus: (liveClassId: string) => `/admin/live-classes/${liveClassId}/status`,
    liveClassFacilitator: (liveClassId: string) => `/admin/live-classes/${liveClassId}/facilitator`,
    liveClassRecording: (liveClassId: string) => `/admin/live-classes/${liveClassId}/recording`,
    liveClassAttendance: (liveClassId: string) => `/admin/live-classes/${liveClassId}/attendance`,
    completionRequirements: (courseId: string) => `/admin/courses/${courseId}/completion-requirements`,
    certificateTemplate: (courseId: string) => `/admin/courses/${courseId}/certificate-template`,
    certificates: (courseId: string) => `/admin/courses/${courseId}/certificates`,
    issueCertificate: (courseId: string, accountId: string) => `/admin/courses/${courseId}/certificates/${accountId}/issue`,
    revokeCertificate: (certificateId: string) => `/admin/certificates/${certificateId}/revoke`,
    announcements: "/admin/announcements",
    announcementStatus: (announcementId: string) => `/admin/announcements/${announcementId}/status`,
  },
  student: {
    dashboard: "/student/dashboard",
    courses: "/student/courses",
    learning: (courseId: string) => `/student/courses/${courseId}/learning`,
    assessment: (assessmentId: string) => `/student/assessments/${assessmentId}`,
    startAttempt: (assessmentId: string) => `/student/assessments/${assessmentId}/attempts`,
    submitAttempt: (attemptId: string) => `/student/attempts/${attemptId}/submit`,
    assessmentResults: "/student/assessment-results",
    assessmentResult: (assessmentId: string) => `/student/assessments/${assessmentId}/results`,
    attemptResult: (attemptId: string) => `/student/attempts/${attemptId}/result`,
    submissions: "/student/submissions",
    courseSubmissions: (courseId: string) => `/student/courses/${courseId}/submissions`,
    submission: (submissionId: string) => `/student/submissions/${submissionId}`,
    submissionFile: (submissionId: string) => `/student/submissions/${submissionId}/files/upload`,
    submitSubmission: (submissionId: string) => `/student/submissions/${submissionId}/submit`,
    assignments: "/student/assignments",
    assignment: (submissionId: string) => `/student/assignments/${submissionId}`,
    liveClasses: "/student/live-classes",
    liveClass: (liveClassId: string) => `/student/live-classes/${liveClassId}`,
    certificates: "/student/certificates",
    completion: (courseId: string) => `/student/courses/${courseId}/completion`,
    certificate: (courseId: string) => `/student/courses/${courseId}/certificate`,
    replays: "/student/replays",
    studySessions: "/student/study-sessions",
    completeStudySession: (sessionId: string) => `/student/study-sessions/${sessionId}/complete`,
    studySummary: "/student/study-sessions/summary",
  },
  facilitator: {
    dashboard: "/facilitator/dashboard",
    students: (courseId: string) => `/facilitator/courses/${courseId}/students`,
    liveClasses: (courseId: string) => `/facilitator/courses/${courseId}/live-classes`,
    attendance: (liveClassId: string) => `/facilitator/live-classes/${liveClassId}/attendance`,
    assessmentResults: (courseId: string) => `/facilitator/courses/${courseId}/assessment-results`,
    submissions: (courseId: string) => `/facilitator/courses/${courseId}/submissions`,
    reviewAttempt: (attemptId: string) => `/facilitator/attempts/${attemptId}/review`,
    reviewSubmission: (submissionId: string) => `/facilitator/submissions/${submissionId}/review`,
  },
  courses: {
    list: "/courses",
    detail: (courseId: string) => `/courses/${courseId}`,
    progress: (courseId: string) => `/courses/${courseId}/progress-events`,
  },
  announcements: {
    feed: "/announcements",
    read: (announcementId: string) => `/announcements/${announcementId}/read`,
    readAll: "/announcements/read-all",
  },
  certificateVerification: (certificateNumber: string) => `/certificates/${certificateNumber}/verify`,
  health: "/health",
} as const;
